### ISSUE TITLE
The easiest way to get the Hamiltonian in second quantization?

### ISSUE THREAD

**Issue by overshiki** [frankwswang/Quiqbox.jl#57]
Hi,
I would like to get the Hamiltonian in the second quantization after HF calculation, i.e. the coefficient matrix of the Hamiltonian in the Fock space given the basis set calculated by HF method. This is the first step of post-HF method, including FCI and quantum computing algorithms(such as VQE) I'm working on. 

I did a little bit of review of the `Quiqbox.jl` code, and found that maybe I can do it using functions provided by `src/Integrals/OneBody.jl` and `src/Integrals/TwoBody.jl`, following the Slater's rules.

Do you have any suggestions for this, and what is the easiest way to achieve this in `Quiqbox.jl` ?

**Comment by frankwswang** [comment]
Hi @overshiki! Quiqbox does not provide the function to directly realize that, which I assume is getting h_ij and h_ijkl on the basis of the molecular orbitals, right? I do plan to implement features to connect better to second quantization and post-HF method calculations in the future. 

As for now, it's fairly simple to achieve your goal with functions already existing in Quiqbox.

First, you need the coefficient matrix `C` for the molecular orbitals on the basis of your initial basis functions. You can get it from the field `.C` of the returned object (of type `HFfinalVars`) from `runHF`. Next, you can use [`coreH`](https://frankwswang.github.io/Quiqbox.jl/stable/coreFunction/#Quiqbox.coreH) and [`eeInteractions`](https://frankwswang.github.io/Quiqbox.jl/stable/coreFunction/#Quiqbox.eeInteractions) to generate the 1-body Hamiltonian part and 2-body Hamiltonian part based on the initial basis set. Then, use the `C` to transform them onto the basis of the molecular orbitals.

A slightly alternative solution would be: 
First, construct the molecular orbital set from `C` and the initial basis set. This can be achieved in Quiqbox through simple [linear operations](https://frankwswang.github.io/Quiqbox.jl/stable/basis/#Linear-combinations-of-basis-functions) like:
```
julia> using Quiqbox

julia> bs = genBasisFunc.([rand(3) for _=1:2], "STO-3G") |> flatten
2-element Vector{BasisFunc{0, 3}}:
 BasisFunc{0, 3}(center, gauss)[X⁰Y⁰Z⁰][0.3094086399, 0.866642077, 0.2275035836]
 BasisFunc{0, 3}(center, gauss)[X⁰Y⁰Z⁰][0.4967536832, 0.6369221654, 0.3466909867]

julia> C = rand(2,2)
2×2 Matrix{Float64}:
 0.762431  0.770003
 0.57282   0.119082

julia> bs2 = [sum(c.*bs) for c in eachcol(C)]
2-element Vector{Quiqbox.BasisFuncMix{2, 6}}:
 Quiqbox.BasisFuncMix{2, 6}(BasisFunc, param)
 Quiqbox.BasisFuncMix{2, 6}(BasisFunc, param)
```
Then input the molecular basis set into `coreH` and `eeInteractions` to get your results. Depending on the size and structure of your basis set, the efficiency of those two solutions might be quite different.

I hope this helps!

**Comment by frankwswang** [comment]
Hi @overshiki! Do you have more questions regarding this issue? If not, I'll close the issue.

**Comment by overshiki** [comment]
Hold on please, I'm testing the idea and may have some issues in the coming days.

**Comment by overshiki** [comment]
Hi @frankwswang 
I just tried to implement the second method in your suggestion. However, I found one weird thing: for LiH system, the number of orbitals generated by genBasisFunc is 4, while the C matrix after HF calculation is 6 by 6. I believe the number of orbitals should be 6, but don't know why genBasisFunc behaved this way. Below is the code to reproduce the result:
```julia
using Quiqbox

bohr = 1.8897259886

bond_length = 0.275 * bohr
nuc = ["H", "Li"]
nucCoords = [[0.0, 0.0, 0.0], [0.0, 0.0, bond_length]]

bs = map(nucCoords, nuc) do c, n 
    genBasisFunc(c, ("STO-3G", n))
end |> flatten
resRHF = runHF(bs, nuc, nucCoords)
C = resRHF.C[1]
@show size(bs), size(C)

```
the result is
```julia
(size(bs), size(C)) = ((4,), (6, 6))
```

Do you have any idea about what happened here?

**Comment by frankwswang** [comment]
Hi @overshiki!
If you use `typeof` to inspect the type of each element in `bs`:
```
julia> typeof.(bs)
4-element Vector{DataType}:
 BasisFunc{0, 3}
 BasisFunc{0, 3}
 BasisFunc{0, 3}
 BasisFuncs{1, 3, 3}
```
You can see that the first 3 elements are [`BasisFunc`](https://frankwswang.github.io/Quiqbox.jl/stable/coreType/#Quiqbox.BasisFunc), each corresponding to a spatial basis function. However, the 4th element is a [`BasisFuncs`](https://frankwswang.github.io/Quiqbox.jl/stable/coreType/#Quiqbox.BasisFuncs), a collection of all the orbitals (spatial basis functions) within the subshell p (l=1).

Both `BasisFunc` and `BasisFuncs` are a subtype of `FloatingGTBasisFuncs`. Specifically, 
```
BasisFunc{𝑙, GN} <: FloatingGTBasisFuncs{𝑙, GN, 1}

BasisFuncs{𝑙, GN, ON} <: FloatingGTBasisFuncs{𝑙, GN, ON}
```
where `𝑙` is the orbital angular momentum quantum number, `GN` is the number of GTO used to construct each orbital, and `ON` is the number of orbitals.

You can `decompose` a `BasisFuncs` into a `Vector` of the basis functions it represents by
```
julia> decompose(bs[4]) |> vec
3-element Vector{BasisFunc{1, 3}}:
 BasisFunc{1, 3}(center, gauss)[X¹Y⁰Z⁰][0.0, 0.0, 0.5196746469]
 BasisFunc{1, 3}(center, gauss)[X⁰Y¹Z⁰][0.0, 0.0, 0.5196746469]
 BasisFunc{1, 3}(center, gauss)[X⁰Y⁰Z¹][0.0, 0.0, 0.5196746469]
```

**Comment by overshiki** [comment]
Hi @frankwswang 
Thanks for your explanation! It is really helpful and I now successfully got the one-body and two-body integral for the Hamiltonian. 

However, I do meet one performance issue: the calculation of the integral is much slower than that of `openfermion`:

For LiH calculation, with `6 * 6` one-body integral and `6 * 6 * 6 * 6` two-body integral, `openfermion` only takes 0.14s, while `Quiqbox.jl` takes 44.7s, around 300x slower...
To reproduce the result, please refer to this [gist](https://gist.github.com/overshiki/c9f61217b0ce0fd66ecc395c7ba652dc)

I'm just wondering what happened here, and is there any way to solve this problem?

**Comment by frankwswang** [comment]
Hi @overshiki! If you want to benchmark the performance of a Julia package, I'd suggest you use a more appropriate package [BenchmarkTools.jl](https://github.com/JuliaCI/BenchmarkTools.jl) to get a more accurate evaluation.

As for the slow performance of Quiqbox, it's somewhat expected for using the second method as I mentioned here:

> Depending on the size and structure of your basis set, the efficiency of those two solutions might be quite different.

Since Quiqbox hasn't provided functions to natively realize the feature you asked for, even though the work-around syntax might be simple, the performance is not optimized. Specifically, calculating the `h_pqrs` with respect to the molecular orbitals is a heavy tensor contraction process that can take up a lot of computing resources without specialized optimization.

If efficiency is your priority, you can use another Julia package [TensorOperations.jl](https://github.com/Jutho/TensorOperations.jl) to directly rotate the one-body integrals and two-body integrals with the `C` matrix. Here is a small adaptation for your code that will dramatically speed up the process:

```
using Quiqbox
using TensorOperations # first install this package separately

bohr = 1.8897259886

function calc_Hamiltonian_coeff2()
    bond_length = 0.275 * bohr
    nuc = ["H", "Li"]
    nucCoords = [[0.0, 0.0, 0.0], [0.0, 0.0, bond_length]]

    bs = map(nucCoords, nuc) do c, n 
        genBasisFunc(c, ("STO-3G", n))
    end |> flatten

    m = basisSize.(bs) |> sum
    b = GTBasis(bs)
    
    resRHF = runHF(b, nuc, nucCoords, printInfo=false)
#     println("Quiqbox:")
#     println("bond length = ", bond_length)
#     @show resRHF.Ehf

    C = resRHF.C[1]

    eeI = b.eeI
    cH = b.getHcore(nuc, nucCoords)
    pq = Array{Float64}(undef, m,m)
    pqrs = Array{Float64}(undef, m,m,m,m)

    @tensor begin # macro provided by TensorOperations
        pq[i,j] = cH[a,b] * C[a,i] * C[b,j]
        pqrs[i,j,k,l] = eeI[a,b,c,d] * C[a,i] * C[b,j] * C[c,k] * C[d,l]
    end

#     @show size(pqrs)
#     @show size(pq)

    return pq, pqrs
end 
```

I think if you use this method, the speed of the code should be at least comparable to the OpenFermion, if not faster. Although, one thing to mention is that Quiqbox does not officially support multi-threading so far and I'm not sure if OpenFermion has such a feature so that could also lead to performance differences related to your machine's specs.

**Comment by overshiki** [comment]
Hi @frankwswang 
Thanks a lot for the help! Yes, this new implementation is much faster! It only takes 0.11s for the LiH example above and is now faster than(or at least comparable to) the OpenFermion. I can see that this is actually the first option you mentioned before, i.e using C to transform the one-body and two-body parts of Hamiltonian onto molecular orbitals.

Regarding the performance difference, ideally, the two options should point to the same tensor contract operation, for example, for one-body integral, using einsum, we have:
```julia
H[i,j] = C[i,a]*W[a,r]*H[a,b,r]*W[b,r]*C[b,j]
```
where `r` is the index that stands for the grid in real space, which is much larger than any other indices. 

The difference between the two options is the order of the contraction, while the first one is
```
H[i,j] = C[i,a]*(W[a,r]*H[a,b,r]*W[b,r])*C[b,j]
```
and the second option is
```
H[i,j] = (C[i,a]*W[a,r])*H[a,b,r]*(W[b,r]*C[b,j])
```

I can now see in most cases, the first option will always be the cheapest one, am I right about this?

**Comment by frankwswang** [comment]
Hi @overshiki! 
I'm glad it finally worked out! I have put the feature request of including a function like `calc_Hamiltonian_coeff` in my dev note. Thanks! 

If things go smoothly, I'll implement it in the next major release (v0.4.0) because I think it's a very useful feature as you suggested! Do you have more questions regarding this issue thread? If not, I'll close it soon.

**Comment by overshiki** [comment]
Hi @frankwswang 
> If things go smoothly, I'll implement it in the next major release (v0.4.0) because I think it's a very useful feature as you suggested! 

That's cool! Thanks!

> Do you have more questions regarding this issue thread? If not, I'll close it soon.

sure, it's OK for me to have it closed.
